//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dopravio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        //public virtual DbSet<driver> driver { get; set; }
        //public virtual DbSet<employee> employee { get; set; }
        //public virtual DbSet<OpStatistics> OpStatistics { get; set; }
        //public virtual DbSet<repairs> repairs { get; set; }
        //public virtual DbSet<route> route { get; set; }
        //public virtual DbSet<salary_changes> salary_changes { get; set; }
        //public virtual DbSet<serviceman> serviceman { get; set; }
        //public virtual DbSet<timetable> timetable { get; set; }
        //public virtual DbSet<vehicle> vehicle { get; set; }
        //public virtual DbSet<vehicle_category> vehicle_category { get; set; }
    }
}
