//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DP_DAIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary_changes
    {
        public int id_change { get; set; }
        public decimal old_salary { get; set; }
        public decimal new_salary { get; set; }
        public Nullable<System.DateTime> date_change { get; set; }
        public int id_employee { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
