//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DP_DAIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetable
    {
        public int id_journey { get; set; }
        public string link_name { get; set; }
        public System.DateTime departure { get; set; }
        public System.DateTime arrival { get; set; }
        public int id_route { get; set; }
        public int id_vehicle { get; set; }
        public int id_driver { get; set; }
    
        public virtual driver driver { get; set; }
        public virtual route route { get; set; }
        public virtual vehicle vehicle { get; set; }
    }
}
