//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DP_DAIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehicle()
        {
            this.repairs = new HashSet<repairs>();
            this.timetable = new HashSet<timetable>();
        }
    
        public int id_vehicle { get; set; }
        public string name { get; set; }
        public int year_of_manufacture { get; set; }
        public int capacity { get; set; }
        public string status { get; set; }
        public double consumption { get; set; }
        public decimal cost_price { get; set; }
        public bool wheelchair_accessible { get; set; }
        public int id_category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<repairs> repairs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timetable> timetable { get; set; }
        public virtual vehicle_category vehicle_category { get; set; }
    }
}
